# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-_OeB2xLxnOrtQp_1YdoWuo51Q3jcsp
"""

import random

text = """
Artificial Intelligence is transforming the world.
Artificial Intelligence helps in automation.
Automation improves productivity and efficiency.
"""

words = text.split()

markov_chain = {}

for i in range(len(words) - 1):
    word = words[i]
    next_word = words[i + 1]

    if word not in markov_chain:
        markov_chain[word] = []

    markov_chain[word].append(next_word)

current_word = random.choice(words)
generated_text = [current_word]

for _ in range(20):
    if current_word in markov_chain:
        current_word = random.choice(markov_chain[current_word])
        generated_text.append(current_word)
    else:
        break

print("Generated Text:")
print(" ".join(generated_text))